version: '2'

services:

  datanode:
    image: jayjohnson/datanode:1.0.3
    container_name: "datanode"
    hostname: "datanode"
    env_file: 
      - ./env/dev.env
    volumes:
      - .:/opt/work
    network_mode: "host"

