version: '2'

services:

  datanode:
    image: jayjohnson/datanode:1.0.2
    container_name: "datanode"
    hostname: "datanode"
    env_file: 
      - ./env/dev.env
    volumes:
      - ./data:/opt/work/data
      - ./env:/opt/work/env
      - ./bins:/opt/work/bins
      - ./configs:/opt/work/configs
      - ./src:/opt/work/src
    network_mode: "host"

