version: '2'

services:

  datanode:
    image: jayjohnson/datanode:1.0.3
    container_name: "datanode"
    hostname: "datanode"
    env_file: 
      - ./env/x11-dev.env
    environment:
      - XAUTHORITY=/root/.Xauthority
      - DISPLAY=unix${DISPLAY}
    volumes:
      - ${XAUTHORITY}:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/opt/work
    network_mode: "host"

